def err = null
try {
    node('testslave') {
        // Main pipeline code goes here
	sh "hostname" 
    }
} catch (caughtError) { //End of Try
    err = caughtError
    currentBuild.result = "FAILURE"
} finally {
    (currentBuild.result != "ABORTED") && node("master") {
        // Send e-mail notifications for failed or unstable builds.
        // currentBuild.result must be non-null for this step to work.
        //step(){
	//	sh "echo 'echo Sending e-mail'"
	//	}
     step([$class: 'CopyArtifact', filter: '*.war', fingerprintArtifacts: true, projectName: 'war', selector: [$class: 'StatusBuildSelector', stable: false]])
 }
    if (err) {
        throw err
    }
}






