try {

node {
    stage('Build') {
        try { 
    parallel testslave: {
        node('testslave') {
		stage('SCM checkout'){
            checkout scm }
            try {
		stage('Build hostname testslave'){
                sh 'hostname'
            }
		}
	    catch (Exception exc) {
            	echo 'Something failed in testslave!'
		}	
            finally {
                sh 'whoami'
            	}
        }
    },
    testslave2: {
        node('testslave2') {
            checkout scm
            try {
                sh 'hostname'
                }
            finally {
                sh 'whoami'
            }

        }
    }
  
		
        }
        catch (Exception exc) {
            echo 'Something failed, I should sound the klaxons!'
		            
        }
    }
}
} catch (Exception exc) {
            echo 'Something failed, I should sound the klaxons!'

} finally { echo 'last finaly statement'}
