version: "3"
services:
  web:
    #replace username/repo:tag with your name and image details
    #image: masmix/friedlyhello:1.0
#    image: centos4.localdomain/masmix/friedlyhell
    image:  192.168.56.102:5000/masmix/friedlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
