pipeline {
    agent { docker { image 'maven:3.3.3' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                //print pure docker ps
                                        def DockerPsStdOut = sh (
                                            script: 'docker ps',
                                            returnStdout: true
                                        )
                                        echo DockerPsStdOut
            }
        }
    }
}
