pipeline {
 agent any
 stages {
  stage('Run Tests') {
   steps {
   node('testslave') {
          sh "hostname"
	sh "ls -la"
	sh "pwd"
//	sh "python docker-api-training/hello-flask/run-container.py"		
}
      node('testslave2'){
          sh "hostname" }
   }
  }
  stage('Deploy') {
   parallel {
    stage('Dev') {
      steps {
      node('testslave') {
		sh "hostname"}
      node('testslave2'){
		sh "hostname" }
		 }
    }
    stage('QA') {
      steps {
      node('testslave') {
                sh "hostname"}
      node('testslave2'){
                sh "hostname" }
      
     }
    }
   }
  }
 }
}

