pipeline {
 agent any
 stages {
  stage('Run Tests') {
   steps {
    sh "echo stage Run Test"
   }
  }
  stage('Deploy') {
   parallel {
    stage('Dev') {
     when {
      branch 'master'
     }
     steps {
      echo 'hello master'
     }
    }
    stage('QA') {
     steps {
      echo 'hello stable'
     }
    }
   }
  }
 }
}

