version: '3'
services:
  #git-server:
  #  build: ./git
  #  ports:
  #    - "2222:22"
  #  restart: always
  #  container_name: git-server
  #  ports:
  #    - "2222:22"
  #  volumes:
  #  - /home/wojtek/git-server/keys:/git-server/keys
  #  - /home/wojtek/git-server/repos:/git-server/repos
  #  networks:
  #       jenkins-net:
  #         aliases:
  #          - git-server
  #tomcat:
  #  build: ./tomcat
  #  ports:
  #    - "8080:8080"
  #  restart: always
  #  container_name: tomcat
  #  networks:
  #       jenkins-net:
  #         aliases:
  #          - tomcat
  #sonarqube:
  #  build: ./sonarqube
  #  ports:
  #    - "9000:9000"
  #    - "9092:9092"
  #  restart: always
  #  container_name: sonarqube
  #  networks:
  #       jenkins-net:
  #         aliases:
  #          - sonarqube
  #nexus:
  #  build: ./nexus
  #  ports:
  #    - "8081:8081"
  #  restart: always
  #  container_name: nexus
  #  networks:
  #       jenkins-net:
  #         aliases:
  #          - nexus
  #selenium_hub:
  #  build: selenium_hub
    #image: selenium/hub:3.14.0-arsenic
  #  ports:
   #   - "4444:4444"
   # restart: always
   # container_name: selenium_hub
   # networks:
   #      jenkins-net:
   #        aliases:
    #        - selenium_hub
  #selenium_node_firefox:
  #  build: ./selenium_node_firefox
  #  #image: selenium/node-firefox:3.14.0-arsenic
   # depends_on:
   #   - selenium_hub
   # restart: always
  #  container_name: selenium_node_firefox
   # environment:
   #   - HUB_HOST=selenium_hub
   #   - HUB_PORT=4444
   # networks:
   #      jenkins-net:
  #         aliases:
  #          - selenium_node_firefox
  #selenium_node_chrome:
  #  build: ./selenium_node_chrome
  #  #image: selenium/node-chrome:3.14.0-arsenic
   # depends_on:
   #   - selenium_hub
   # restart: always
   # container_name: selenium_node_chrome
   # environment:
   #   - HUB_HOST=selenium_hub
   #   - HUB_PORT=4444
   # networks:
   #          jenkins-net:
   #            aliases:
   #             - selenium_node_chrome
  master:
    image: masmix/jenkins_master:latest
    #build: ./jenkins-master
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
#  nginx:
#    image: jenkins_nginx:latest
    #build: ./jenkins-nginx
#    ports:
#      - "80:80"
#    networks:
#      - jenkins-net
  slave:
    image: masmix/jenkins_slave:latest
    #build: ./jenkins-slave
    networks:
      - jenkins-net
    #deploy:
    #    mode: replicated
    #    replicas: 1
  proxy:
    image: masmix/jenkins_proxy:latest
   #ld: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     jenkins-net:
       aliases:
        - proxy1
#    image: ehazlett/docker-proxy:latest
#    #    command: -i
#    #    volumes:
#    #      - /var/run/docker.sock:/var/run/docker.sock
#    #    networks:
#    #      jenkins-net:
#    #        aliases:
#    #          - proxy1 
volumes:
 jenkins-data:
 jenkins-log:
networks:
 jenkins-net:
#
