node {
    def mvnHome
    stage('Preparation') { // for display purposes
        //git 'https://github.com/jglick/simple-maven-project-with-tests.git'
        //git 'git@172.17.0.4:/git-server/repos/myrepo.git'
        //dir('complete')
        // {


        checkout([$class: 'GitSCM',
                  branches: [[name: '*/master']],
                  doGenerateSubmoduleConfigurations: false,
                  extensions: [[$class: 'RelativeTargetDirectory',
                                relativeTargetDir: '']],
                  submoduleCfg: [],
                  userRemoteConfigs: [[url: 'ssh://git@git-server/git-server/repos/myrepo.git']]])
        //}

        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.

        mvnHome = tool 'maven1'
    }

    stage('SonarQube analysis') {
	ws('workspace/pipeline2/sonar-project.properties') {
        // requires SonarQube Scanner 2.8+
        def scannerHome = tool 'sonar1';
        echo scannerHome;
        withSonarQubeEnv('sonar1') {
            sh "${scannerHome}/bin/sonar-scanner -X -Dsonar.projectKey=my:project_2017a -Dsonar.projectName=My project_2017a -Dsonar.projectVersion=1.0 -Dsonar.sources=."
        }
    }
}




    stage('Build') {
        // Run the maven build
        if (isUnix()) {
            sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package -f complete"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package -f complete/)
        }
    }
    stage('Results') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.jar'
    }
}
