version: '3'
services:
  git-server:
    build: ./git
    ports:
      - "2222:22"
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - /home/wojtek/git-server/keys:/git-server/keys
    - /home/wojtek/git-server/repos:/git-server/repos
  tomcat:
    build: ./tomcat
    ports:
      - "8080:8080"
    restart: always
    container_name: tomcat
  sonarqube:
    build: ./sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    restart: always
    container_name: sonarqube
  nexus:
    build: ./nexus
    ports:
      - "8081:8081"
    restart: always
    container_name: nexus
  selenium_hub:
    build: selenium_hub
    #image: selenium/hub:3.14.0-arsenic
    ports:
      - "4444:4444"
    restart: always
    container_name: selenium_hub
  selenium_node_firefox:
    build: ./selenium_node_firefox
    #image: selenium/node-firefox:3.14.0-arsenic
    depends_on:
      - selenium_hub
    restart: always
    container_name: selenium_node_firefox
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
  selenium_node_chrome:
    build: ./selenium_node_chrome
    #image: selenium/node-chrome:3.14.0-arsenic
    depends_on:
      - selenium_hub
    restart: always
    container_name: selenium_node_chrome
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
  master:
    build: ./jenkins-master
    ports:
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
  nginx:
    build: ./jenkins-nginx
    ports:
      - "80:80"
    networks:
      - jenkins-net
  slave:
    build: ./jenkins-slave
  proxy:
    build: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     jenkins-net:
       aliases:
        - proxy1
#    image: ehazlett/docker-proxy:latest
#    #    command: -i
#    #    volumes:
#    #      - /var/run/docker.sock:/var/run/docker.sock
#    #    networks:
#    #      jenkins-net:
#    #        aliases:
#    #          - proxy1 
volumes:
 jenkins-data:
 jenkins-log:
networks:
 jenkins-net:
#
